# Generated by Django 2.2.4 on 2020-03-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sap_id', models.IntegerField(unique=True)),
                ('index', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specification', serialize=False, to='products.Product')),
                ('internal_diameter_target', models.FloatField()),
                ('internal_diameter_tolerance_top', models.FloatField()),
                ('internal_diameter_tolerance_bottom', models.FloatField()),
                ('external_diameter_target', models.FloatField()),
                ('external_diameter_tolerance_top', models.FloatField()),
                ('external_diameter_tolerance_bottom', models.FloatField()),
                ('wall_thickness_target', models.FloatField()),
                ('wall_thickness_tolerance_top', models.FloatField()),
                ('wall_thickness_tolerance_bottom', models.FloatField()),
                ('length_target', models.FloatField()),
                ('length_tolerance_top', models.FloatField()),
                ('length_tolerance_bottom', models.FloatField()),
                ('flat_crush_resistance_target', models.IntegerField()),
                ('flat_crush_resistance_tolerance_top', models.IntegerField()),
                ('flat_crush_resistance_tolerance_bottom', models.IntegerField()),
                ('moisture_content_target', models.IntegerField()),
                ('moisture_content_tolerance_top', models.IntegerField()),
                ('moisture_content_tolerance_bottom', models.IntegerField()),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('maximum_height_of_pallet', models.FloatField()),
                ('quantity_on_the_pallet', models.IntegerField()),
                ('pallet_protected_with_paper_edges', models.CharField(choices=[('Y', 'Tak'), ('N', 'Nie')], default=('Y', 'Tak'), max_length=10)),
                ('pallet_wrapped_with_stretch_film', models.CharField(choices=[('Y', 'Tak'), ('N', 'Nie')], default=('Y', 'Tak'), max_length=10)),
                ('cores_packed_in', models.CharField(choices=[('Horizontal', 'w pozycji pionowej'), ('Vertical', 'w pozycji poziomej'), ('On_carton', 'na kartonach')], default='Horizontal', max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
