# Generated by Django 2.2.4 on 2020-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
