# Generated by Django 2.2.4 on 2020-04-18 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='flat_crush_resistance_target',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Pole integer powinno zawierać liczbę całkowitą', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='moisture_content_target',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Pole integer powinno zawierać liczbę całkowitą', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Pole integer powinno zawierać liczbę całkowitą', regex='^[0-9]*$')]),
        ),
    ]
