# Generated by Django 2.2.10 on 2020-10-22 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200918_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sap_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='Numer SAP powinien składać się z dokładnie 7 cyfr', regex='^([0-9]{7})$')]),
        ),
    ]
