# Generated by Django 2.2.10 on 2020-10-22 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201022_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sap_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='Numer partii powinien składać się z dokładnie 8 cyfr', regex='^([0-9]{8})$')]),
        ),
    ]
