language: python
python:
  - "3.7"

services:
  - mysql

install:
  - pip install -r requirements_test.txt

# Run scripts specified in Jobs rather than one global script.
script: skip

jobs:
  include:
    - stage: lint
      script: python -m flake8 --statistics --exclude venv_cx_1122020 --ignore=E265,E501,F401,W605,W504,F841,*migrations --max-line-length 120 .

    - stage: test
      script: python manage.py test apps --failfast

cache:
  - pip
  - directories:
    # Cache the virtualenv packages folder so virtualenv doesn't waste
    # time installing locally cached packages
    - '/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages'

