# Generated by Django 2.2.10 on 2020-10-29 15:18

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cxuser',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterField(
            model_name='cxuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Użytkownik o podanym loginie już istnieje!.'}, help_text='Wymagane. Musi się składać z dokładnie 5 liter.', max_length=150, unique=True, validators=[apps.users.models.CxUsernameValidator()], verbose_name='username'),
        ),
    ]
