# Generated by Django 2.2.10 on 2020-10-29 15:21

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201029_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cxuser',
            options={'verbose_name': 'Uzytkownik', 'verbose_name_plural': 'Uzytkownicy'},
        ),
        migrations.AlterField(
            model_name='cxuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Uzytkownik o podanym loginie już istnieje!.'}, help_text='Wymagane. Musi się skladac z dokladnie 5 liter.', max_length=150, unique=True, validators=[apps.users.models.CxUsernameValidator()], verbose_name='username'),
        ),
    ]
