# Generated by Django 2.2.10 on 2020-11-21 18:38

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201029_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxuser',
            name='username',
            field=models.CharField(error_messages={'inactive': 'Użytkownik o podanym loginie jest nieaktywny.', 'invalid_login': 'Podaj właściwy login i hasło. Zwróć uwagę na wielkość znaków.', 'unique': 'Uzytkownik o podanym loginie już istnieje!.'}, help_text='Wymagane. Musi się skladac z dokladnie 5 liter.', max_length=150, unique=True, validators=[apps.validators.CxUsernameValidator()], verbose_name='username'),
        ),
    ]
