# Generated by Django 2.2.4 on 2020-03-17 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_sap_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='SAP id klienta musi być numerem składającym się z 6 cyfr', regex='^([0-9]{6})$')]),
        ),
    ]
