# Generated by Django 2.2.4 on 2020-04-18 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200317_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_sap_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='Numer SAP powinien składać się z dokładnie 6 cyfr', regex='^([0-9]{6})$')]),
        ),
    ]
